[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

[project]
name = "cads-adaptors"
description = "CADS data retrieve utilities to be used by adaptors"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering"
]
dynamic = ["version"]
dependencies = ["cacholote", "multiurl"]

[tool.coverage.run]
branch = true

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
    "cdsapi",
    "multiurl"
]
ignore_missing_imports = true

[tool.ruff]
# Black line length is 88, but black does not format comments.
line-length = 110
select = [
  # pyflakes
  "F",
  # pycodestyle
  "E",
  "W",
  # isort
  "I",
  # pydocstyle
  "D",
]
ignore = [
  # pydocstyle: Missing Docstrings
  "D1",
  # pydocstyle: numpy convention
  "D107",
  "D203",
  "D212",
  "D213",
  "D402",
  "D413",
  "D415",
  "D416",
  "D417",
  "D205"
]

[tool.setuptools]
packages = ["cads_adaptors"]

[tool.setuptools_scm]
write_to = "cads_adaptors/version.py"
write_to_template = '''
# Do not change! Do not track in version control!
__version__ = "{version}"
'''
