name: Update packages that depends on cads-adaptors

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"


jobs:
  update-downstream-packages:
    name: Pull request to update packages
    uses: ecmwf-projects/cads-build-farm/.github/workflows/update-downstream-packages.yaml@main
    with:
      package-ref: "CADS_ADAPTORS_REF"
      repositories: |
        ecmwf-projects/cads-processing-api-service
        ecmwf-projects/cads-worker
        ecmwf-projects/cads-broker
    secrets: inherit
